### SVD (Singular Value Decompostion)

* An application of linear algebric algorithm SVD used in dimensionality reduction.

In [2]:
#importing libraries
import pandas as pd
import numpy as np
from scipy.linalg import svd

In [4]:
# random matrix data
A = np.array([[1,2,3,4,5,6,7,8,9,10],
        [11,12,13,14,15,16,17,18,19,20],
        [21,22,23,24,25,26,27,28,29,30]])

In [5]:
# printing the matrix
A

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [7]:
# Singular Value Decomposition
U,s,Vt = svd(A)
# create mxn Sigma matrix
Sigma = np.zeros((A.shape[0],A.shape[1]))
# Populate Sigma with zeroes
Sigma[:A.shape[0], :A.shape[0]] = np.diag(s)
#select of only two features
n_elements = 2
Sigma = Sigma[:,:n_elements]
Vt = Vt[:n_elements,:]
#recontruct of original matrix
B = U.dot(Sigma.dot(Vt))
print('Reconstructing the approximated version of original matrix')
print(B)
# transform ( a description of original matrix of low rank)
T = U.dot(Sigma)
print('Generating the transformed matrix with low rank')
print(T)
# another way of generating the same transformed matrix with low rank
T = A.dot(Vt.T)
print('Another way of presenting the transformed matrix')
print(T)

Reconstructing the approximated version of original matrix
[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]]
Generating the transformed matrix with low rank
[[-18.52157747   6.47697214]
 [-49.81310011   1.91182038]
 [-81.10462276  -2.65333138]]
Another way of presenting the transformed matrix
[[-18.52157747   6.47697214]
 [-49.81310011   1.91182038]
 [-81.10462276  -2.65333138]]
